### ISSUE TITLE
PRIV Autumn Cleanup

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#1006]
## Description

With the usage now well in place, take lessons learned and improve PRIV for more consistency with the current practice, and easier use.

## Sub-tasks

- [ ] #1004 
- [ ] #1002 
- [ ] blindnet-io/devrel-management/issues/77
- [ ] blindnet-io/product-management/issues/961
- [ ] #1007
- [ ] blindnet-io/devrel-management/issues/53
