### ISSUE TITLE
Autumn '22 Storage Improvements

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#1009]
## Description

I am creating this issue as a placeholder for different storage-related improvements that we have talked about in TechTalk.

The idea is to have a versatily architecture for storage connectors, so that we can host storage connectors for clients (and have one storage connector used by several clients, configurable through a graphic interface) and at the same time let clients write (and host) their own connectors. Document it, and have it operational (with few connectors) in dogfood.

## Sub-tasks

- [ ] #999 
- [ ] #985 
- [ ] blindnet-io/dogfood/issues/13
- [ ] Mailchimp connector (@milstan will try to make it to see how easy it is and write tutorial)
- [ ] A way to configure blidnet-hosted connectors
