### ISSUE TITLE
Autumn '22 Dashboard Improvements

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#1010]
## Description

We areed to use the existing dashboard (we made for blindnet SDK, for blindnet devkit too). In this issue I list task related to the update.

## Sub-tasks

- [ ] blindnet-io/product-management/issues/989
- [ ] There is a way to configure storage connectors in the dashboard
- [ ] clients can pay with goCardless
- [ ] clients can create their app from the dashboard
- [ ] Dashboard requirements and feature roadmap for winter

**Comment by milstan** [comment]
abandoned in favour of #1014
