### ISSUE TITLE
📑 [Epic]: Define and implement global connectors

### ISSUE THREAD

**Issue by TheKinrar** [blindnet-io/product-management#1013]
## Description

Refactor the storage connector architecture to allow for both custom connectors as we have today, and global connectors, hosted by blindnet and configurable by the user.
Supabase will be used as a first global connector.
Required by https://github.com/blindnet-io/dogfood/issues/13.

## Sub-tasks

- [ ] Define (draft) the new architecture
- [ ] https://github.com/blindnet-io/data-access-component/pull/3
- [ ] Connector SDK changes
- [ ] https://github.com/blindnet-io/dogfood/issues/13
