### ISSUE TITLE
Dashboard 2.0

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#1014]
## Description
Although having a new admin interface / dashboard for the devkit is not our immediate priority (but will be that by year-end), what we are currently doing (connectors, PCE, confguraiton component ...)  is all going to be configurable though the future admin interface. 

So I am creating this issue as a placeholder to collect requirements, and maybe also start progressively building the dashboard as we build the APIs, use it to test the exhaustivity of the API design. I created a [placeholder project](https://github.com/blindnet-io/dashboard-2), where I initated a free boostrap template as a starting point.

### Intended outcome

Minimal but functional dashboard. Further discussion is needed to reduce the scope of work to the minimum, while maximizing usfulness for the clients.

## Requirements

- [x] An admin user can create an account (ideally using a 3rd party identity management solution). This results in creation of an a PCE App
- [ ] An admin user can see their App ID and they can generate authentication keys (using key generator) and see relevant tutorial links for authentication
- [ ] An admin user can configure the PCE (legal bases, consents, types of requests being automatically processed)
- [ ] An admin user can add, configure and remove connectors from a base of connectors we have.
- [ ] An admin user can access all of the DCI functionalities (the component is integrated in the dashboard)
- [ ] An admin user can invite admin and DPO users (ideally using a 3rd party identity management solution). DPO users can only see the DCI, approve and reject requests
- [ ] There is a dashboard devkit connector so that throught Dogfood, any user of the Dashboard can exercise their privacy rights
- [ ] Two ways to get a Privacy Portal (1) embed PRCI in your webpage, and (2) from the dashboard generate a blindnet-hosted page with embedded PRCI, and possibility to confirue a domain record point from their domain to it
- [ ] TBD

## Related tasks
- [x] blindnet-io/privacy-components-web/issues/133
- [ ] #989 
- [ ] blindnet-io/product-management/issues/1013
