### ISSUE TITLE
Refine PRIV

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#706]
> “Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.”
> ― Antoine de Saint-Exupéry

## Goal

Confirm and finalise the design of PRIV.

## Subtasks
- [x] #707 
- [x] #798
- [ ] Include support for representing data about data-transfer abroad (Art 44-50 of GDPR)
- [ ] Further Simplify PRIV for easier understanding and use
- [ ] Add CPRA-support
- [ ] Add HIPPA-support
- [x] Makre PRIV Tutorials to replace examples.md with a more pedagogical format
- [x] Using PRIV in other components, validate it or make changes to it
- [ ] Write an IETF-compliant version of PRIV RFC for submission
- [ ] Make sure Data Categories cover all [Apple Privacy Labels](https://www.apple.com/privacy/labels/) and [Google Play Data Types](https://support.google.com/googleplay/android-developer/answer/10787469?hl=en#zippy=%2Cdata-types) and [Google Play Purposes](https://support.google.com/googleplay/android-developer/answer/10787469?hl=en#zippy=%2Cdata-types%2Cpurposes)
- [x] #822
- [ ] #838
- [ ] Separate PRIV Terms vocabulary from PRIV Events schemas
- [x] #845 

## Stankeholders
@filipblnt - changes and validation throuhg implementation
@noelmace - tutorials
@milstan - simplification and oversight of changes, IETF-compliant format

**Comment by milstan** [comment]
Decided to favor coherence of PRIV with the developped code, and leave PRIV imporvments for later, once more usage-feedback is generated.
