### ISSUE TITLE
[Epic]: Make Privacy Computation Engine

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#709]
## Goal

Make the [Privacy Computation Engine](https://github.com/blindnet-io/product-management/blob/main/refs/high-level-architecture/readme.md#privacy-computation-engine), formerly known as *Data Rights Compiler* Component of the [High Level Architecture](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture)

## Sub-tasks
- [x] blindnet-io/product-management#712
- [x] #725 
- [x] #772 
- [x] Make [Privacy Computation Engine - Customization API](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#customizable-api)
- [x] Decide on the best way to design the Privacy Compiler (rule engine or simple if-then-else tree)
- [x] Make and Test the Privacy Compiler

## Stakeholders
@milstan , @Clementinev - initial draft
Engineering team - test and improvements along the way
@filipblnt - take over the draft and continue improvment through building of other components

**Comment by milstan** [comment]
[PCE](https://github.com/blindnet-io/privacy-computation-engine) has been done in the sens of Q3 goals. Improvements to come in Q4.
