### ISSUE TITLE
[Epic]: Make Schemas

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#710]
## Goal

Make the [Schemas](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#schemas) Component of the [High Level Architecture](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture)

## Sub-tasks

- [x] blindnet-io/product-management#719 
- [x] blindnet-io/product-management#714
- [x] blindnet-io/product-management#713
- [x] #726

## Stakeholders
@milstan , @Clementinev - initial draft
Engineering team - test and improvements along the way
@filipblnt - take over the draft and continue improvment through building of other components

**Comment by milstan** [comment]
I am transfering the issue to @filipblnt as blindnet engineering should now take over this work.

**Comment by milstan** [comment]
All the subtasks are done. Good enough for now. Changes are likely. Closing this issue.
