### ISSUE TITLE
 [Epic]: Define first version of language-agnostic privacy request interoperability vocabulary (PRIV)

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#719]
The goal of this issue to develop a formal vocabulary for expressing Privacy Requests, as a part of the `schemas` component of the [High Level Architecture](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture).

There is a draft of the document [here](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md), alrady a part of the [draft pull request 659](https://github.com/blindnet-io/product-management/pull/659)

There are the following remaining taks:
- [x] blindnet-io/product-ideas#25
- [x] blindnet-io/product-management#708
- [x] blindnet-io/___issue-transfer-buffer#39
- [x] blindnet-io/product-ideas#27
- [x] blindnet-io/product-management#715
- [x] Harmonize language and finalize the document
