### ISSUE TITLE
🔴 [Epic]: build blindnet devkit

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#721]
>*@milstan: I changed this issue's description so that tasks match architecture components. 2022-06-08*
>*@milstan: I changed this issue's description to refine scope and set priorities. 2022-06-25*

## Description

According to [Filip's comment](https://github.com/blindnet-io/product-management/issues/721), which is now considered normative, what we are building is called `blindnet devkit`. It replaces previous tools such as `blindnet API & SDK`, and `Privateform` which will continue to exist as one or more components of `blindnet devkit`.

This issue is a placeholder for high-level action plan for getting to build `blindnet devkit`. This issue is the **TOP PRIORITY** for Product work in the milestone [Q3 2022](https://github.com/blindnet-io/product-management/milestone/36).

### Context

follows https://github.com/blindnet-io/devrel-planning/issues/24#issuecomment-1078928405

### Intended outcome

`blindnet devkit` is a tool set for [privacy-enabled connectedness](https://github.com/blindnet-io/product-management/blob/main/refs/notion-of-privacy/notion-of-privacy.md#privacy-enabled-connectedness). 
The key concepts of `blindnet devkit` are defined in normative documents:
- [High Level Conceptualisation](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-conceptualization)
- [High Level Architecture](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture)

These documents represent a shared conceptualisation, that is (and should be) evolving, but it is considered normative pending any change.

The resulting `blindnet devkit` is a realisation of those normative documents as much as possible. It MAY be incomplete with regards to normative documents, but it MUST NOT be developed in contradiction with anything written in them.

### Key Principles

- Seek to maximise: simplicity, interoperability, atomicity - ability to use only one part of the solution without the others i.e. no overhead). **See [comment](https://github.com/blindnet-io/communication-management/issues/87#issuecomment-1133583909).**
- Focus first on the functionalities that are both (1) needed by the maximum number of prospective clients and (2) differntiating with regards to competition
- Design our system for interoperability with existing Open Source projects. Rather than reimplementing what they do, become their extension. The optimal design of our system is the design in which we extend the functionality of a group of Open Source projects that has the maximal existing adoption
- Reuse other Open Source projects whenever possible (unless there are explicit viable reasons in favour of not doing so)

> The following steps will be better defined with @blindnet-io/engineering based on the conclusions of blindnet-io/devrel-management#27

1. create new generic Open-Source WebDev tools on top of our SDK (especially, allow a more declarative approach by creating a “technical” component library), and rethink the whole architecture of privateform frontend using them
    - Focus on building the generic WebDev tools, and then, rebuild privateform as a demo (using any WebDev library or framework, e.g. we can keep Angular if phase 2 is good enough)
   - Or focus on rebuilding privateform with lightweight tools (like [lit](https://lit.dev/), or even in VanillaJS), and extract generic WebDev tools from it progressively
2. build overlayers for the “_vanilla-web-sdk”_ (i.e. results of phase 3) for all major frameworks (Angular, React, VueJS, etc.) + build / DevX tools (e.g. CLI, generators) if we see fit

### Key Differentiators
The work on this issue seeks to develop distinctive differentiation from competition (as studied [here](https://github.com/blindnet-io/communication-management/pull/141)). The key differentiators pursued are:
- **Automation** - ability to automaticaly process Privacy Requests
- **Interoperability** - ability of Systems to work together, using blindnet devkit, in the context of data exchnage

Features and functionalities that contribute to those **key differentiators** are considered prioritary.

### Specs / Architecture preparation

- [x] https://github.com/blindnet-io/product-management/pull/596
- [x] #742

### Development (< v0.8)

> follow the [MoSCoW method](https://en.wikipedia.org/wiki/MoSCoW_method)

#### Must

- [x] blindnet-io/product-management#710
- [x] blindnet-io/product-management#709
- [x] #762 
- [x] blindnet-io/product-management#720  

#### Should

- [ ] #783
- [x] #781
- [x] #756

#### Could

- [x] blindnet-io/product-management#705

### Further materials and actions

- [ ] blindnet-io/communication-management#87 
- [x] #782
- [x] blindnet-io/communication-management#111 

## Stakeholders

- @filipblnt - leader
- @noelmace - contributor & 0th customer
- @blindnet-io/engineering
- @milstan  - product guidance

**Comment by noelmace** [comment]
Closing this Epic as it seems out of date, and a duplicate of a lot of other ones.
Feel free to reopen if necessary.

**Comment by milstan** [comment]
Hey @noelmace , @jboileau99 , @m4rk055 , @TheKinrar 

We spoke about adding to each milestone what we expect to acheive in it. Here is my proposal for the next few (covering month of August). It's just a proposal, feelf ree to change/challenge/refine as you move throught the work.

Ideally, we reach a meaningful complete realease at each milestone, and ideally by end of Auguest we have as much as possible full system. Then in September we cas see, as a result of testing what are we still missing, what we forgot, and what bugs we need to fix.

p.s. we also need to figure out how to test it - have some sort of demo.

**DevKit v0.3 – 29 July**

PRCI – PCE – DCI connected and can deliver, together, a non-mocked response to a transparency request. The user can make various `TRANSAPRENCY.*` requests and get different answers.

PCE can take in the configuration (RoPA and similar).

First steps of Data Access Component.

**DevKit v0.4 – 12 August**

PRCI covers all demand types. Data Subject can authenticate.
DCI allows to view history of PRIV events, See recommended Responses, modify and send them. See past responses. Settings allow to set automatic responses to certain demands.

PCE and Data Access Component communicate. It is possible to fetch data for `ACCESS` demands.

PCE automates `ACCESS`, `TRANSPARENCY` (for logged and non-logged users), and `REVOKE CONSENT`. All those work in PRCI-PCE-DCI workflow.

**DevKit v0.5 – 26 August**

PRCI/DCI also send e-mail to Data Subjects when there is a response, so they come and see it (e-mail templates configurable at least from the code). All is multilingual.

PCE can take any PRIV event (except Data Captures) and deliver recommendations to any Privacy Request type.

Data Access / Storage can take instructions about data to modify/delete after responses to Privacy Requests or after loss of Legal Base.

**DevKit v0.6 – 02 September**

Large part of feature-set covered. All tested. Bugs, missing features identified.

**Comment by noelmace** [comment]
### Testing and Demoing

Testing and demoing the frontend components is initiated in https://github.com/blindnet-io/privacy-components-web/issues/22, using Storybook and a new "CDN build". In v0.2, 3rd-party devs can already test the PRCI web component using Storybook on https://blindnet-io.github.io/privacy-components-web/, but there is still some more documentation needing our attention.

Testing and demoing backend components directly can be done with either Stoplight or Swagger, depending on what @m4rk055 opts for. I'd recommend using Stoplight for everything (modelling the API for mocking ahead of time, then replacing the OpenAPI definition with the one generated from the component's actual code afterwards, and linking this doc to the API root end-point) to avoid duplication and using too many different tools.

For the Data Access / Storage components, @TheKinrar will develop a demo implementation while creating a first version of the library, as this part is mostly about creating tools to improve the DevX when connecting the DevKit to an _existing_ storage service, to avoid duplication of mappings and other storage related well-known matters.

I'll write content (including tutorials) to showcase these as part of https://github.com/blindnet-io/blindnet.dev/issues/26, and promote them as we go.

**Comment by milstan** [comment]
Thanx. This is unseful. It might interest @Vuk-BN .

**Comment by milstan** [comment]
👏 Thanks to all of your efforts, @Clementinev , @TheKinrar, @noelmace , @jboileau99, @m4rk055 this issue has been done. 

The updated [product-roadmap](https://github.com/blindnet-io/devrel-management/blob/main/docs/roadmap/q3-2022.md) now reflects where we are at Q3, and hints future features our clients may expect. I'll be making a dedicated TOP PRIORITY issue for Q4 product development, that will be a summary of what we discussed.
