### ISSUE TITLE
Refine priorities and development vs. reuse scope of blindnet devkit

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#742]
## Goal

The goal of this issue is to answer the following two questions:
- Out of the total scope of [HLA](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#high-level-component-architecture), what components should be developed and what can and should be reused from existing open source projects?
- In which order should we be developing the components of blindnet devkit?

## Context

One of the key principles, listed in the **_Build blindnet devkit_** issue, is:

- _Design our system for interoperability with existing Open Source projects. Rather than reimplementing what they do, become their extension. The optimal design of our system is the design in which we extend the functionality of a group of Open Source projects that has the maximal existing adoption_

We also want to maximize the work that is distinctive (having in mind that the key differentiations we pursue are [**out-of-the-box automation** and **interoperability**](https://github.com/blindnet-io/communication-management/blob/main/docs/product-marketing/2022/blidnet-devkit-product-spec.md#product-differentiation).

As we also want to generate traction, we want to first be making tools for which we are sure we can quickly generate usage (see this [issue here](https://github.com/blindnet-io/communication-management/issues/162)).

## What is done
Order-wise:
Filip has proposed a [high-level roadmap](https://docs.google.com/spreadsheets/d/1_EvQGtNnh0v8iRa-3pPVmVFqp9vmwQB_Tyu27bx4fOI/edit#gid=0).
Schemas component has been de-facto in the making as the first component being made.

## Subtasks - what still need to be done

- [ ] @noelmace to update about signals from dev community regarding which components might more quickly interest early adopters to test them and get involved with regards to [this issue](https://github.com/blindnet-io/communication-management/issues/162). An ordered list of components, with hints of arguments about why is expected
- [ ] for each component of [HLA](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#high-level-component-architecture) make a list of open-source tools that cover parts of its scope
- [ ] for each component, with regards to parts of scope covered by existing tools, discuss and decide on the opportunity of build vs. reuse (in light of the Context and Goals of this issue)
- [x] Make a decision in which order to proceed with making of the blindnet devkit (in light of the Context and Goals of this issue)

## Who
- @noelmace - for devrel community insights
- @filipblnt - coordinate and move towards an informed decision
- @blindnet-io/engineering - find open source tools, analyse build vs. reuse opportunities, discuss choices
- @Vuk-BN - any market feedback from you is useful here

> **Note**
>
> This issue is not a prerequisite blocking work on the blindnet devkit, however it should be considered as a priority over it, and ideally resolved ASAP so that further development is made according to priorities.

**Comment by filipblnt** [comment]
@m4rk055 @TheKinrar @jboileau99 [This](https://github.com/blindnet-io/communication-management/issues/87#issuecomment-1149196333) comment is probably a good place to start (a few previous in that thread have some more ideas s well).

**Comment by milstan** [comment]
> **If we want to keep the current architecture** After inspecting a number of open source solutions, my suggestion is to develop servers of all the components ourselves. None if the solutions provide extensibility that can easily handle our business logic and reusing them will take more time compared to developing.

Just a note: keeping the current architecture is NOT A REQUIREMENT. It is expected the architecture to change while making blindnet devkit.

However, your concern about ROI of extending an existing solution remains valid, if they do not provide extensibility that can easily handle our business logic.

**Comment by Vuk-BN** [comment]
@MRPbdnt and I have already heard several times that the interoperability protocols to share data with third-parties and still be able to control consent and rights management is a very clear differentiating feature of our software. 

In addition to Privacy Compiler (data governance and automation of privacy requests) and Metadata tagging (Data Capture engine), Interoperability protocols is def the top priority for development.

**Comment by milstan** [comment]
After our discussion today, I think we whould clearly distinguish the following scopes:

## The immediate focus
> What will be developped in Q3 2022 milestone

We want to produce a subset of HLA components, such that:
- it can operate standalone OR it can copearte with complementary solutions (Ethica, BigId - for data cataloguing) the clients of which can easily use blindnet devkit to get an extension of their current functionalities
- It can work for clients building a new system, or for clients having already a working System (with legacy data in a relational database)

It is focused on the key competetive advantage - automatic resolution of Privacy Requests, and Interoperability

Under this assumption:
- the configuration fed to the system is some sort of mapping between database fileds and PRIV terms allowing to produce PRIV metadata (potentially in form of captures and fragments). This can initiatly be done through a file/API call, and then an interface can be provided later.
- Capture Component is reduced only on metadata (maybe also plays a role in remerbering trasnfers - or this is done direclty in Privacy Computation Engine)
- Data Consumer Interface is reduced only on operations on Privacy Requests (not on data view)
- Storage (if made) is reduced to an interface translating instructions of Privacy Computation Engine into database queries
- Privacy Request Capture Interface is reduced to its local scope

## Autumn scope 
> What we'll work on just after that

In addition to previous scope, offers advanced storage system made for privacy - where storage datastructure follows the structure of data-captures, fragments, versions etc. Like an extension of a document database specifically made with privacy in mind. 

This would be the pure-player style version of the devkit, adapted more to document database approach.

## Remaining scope
> What, for now, we don't plan on doing but someone esle can, as this is all public

Global scope of Privacy Request Capture Interface

**Comment by milstan** [comment]
> None if the solutions provide extensibility that can easily handle our business logic and reusing them will take more time compared to developing.

Also @m4rk055 what about open-soruce components for login/identity management. Can we at least use those, and not have to develope those parts of the architecture? Ideally here, in this issue we can find an approch to reduce the scope of what we're making to a most viable minimum.

**Comment by jboileau99** [comment]
Hey guys, here's my thoughts on one way we could prioritize development of the HLA components. What do you think? I've thought about it mainly in terms of maximizing the following priorities:
- Competitive advantage (Automation and Interoperability)
- Attractivity for traction (ability and incentives for client Systems to easily adopt Blindnet devkit - get involved during our development and use it as of launch).

We could begin by developing the following two in parallel (and why):

- Mapping component between client data and capture/fragment model:
    - *Competition Advantage: Interoperability*
        - Demonstrates to users that their data formats can be easily integrated with Blindnet’s components. I could imagine this being perhaps the most crucial requirement for many users, so it seems natural to develop it first.
    - *Attractivity for traction*
        - “Gets the wheels spinning” on how integration of a companies existing systems with Blindnet is possible, encouraging involvement as we develop
- [Privacy Request Capture Interface](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#privacy-request-capture-interface) Component:
    - *Attractivity for traction*
        - Allows us to expose an application of PRIV and get users familiar and involved with it as early as possible
        - “Easier” component to begin with, given that it can be used (I believe) without the Capture Component, Storage Component, or the rest of the Privacy Computation Engine (Privacy Compiler and Customization API).
    - *Competition Advantage: Interoperability*
        - Users could plug this component into their existing systems to handle privacy requests for data subjects
    - *Competition Advantage: Automation*
        - While there is less potential for automation without the Privacy Computation Engine, we can highlight that as a feature in the near term once the Engine is developed
        - Automation isn’t inhibited by this component existing by itself; plenty of potential for clients to develop their own around the component, which may give us insights in developing the Data Consumer Interface and Privacy Computation Engine

**After these two**, I think the Capture Component is the clear candidate to be developed next, because:

1. We maintain and demonstrate interoperability by developing this after the mapping component (above).
2. The Data Consumer and Storage Components require this Capture Component to be completed first (I think?).

For the remaining Data Consumer Interface, Privacy Computation Engine (Privacy Compiler and Customization API), and Storage Component, I'm less sure about which to prioritize but could imagine different reasons which would guide developing one before the other:

- Data Consumer Interface
    - Developing this seems like a natural next step after completing the Data Capture component, as it will now allow users [these functionalities](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#data-consumer-interface) related to their data
- Privacy Computation Engine
    - This supplements the functionality of both the Privacy Request Capture Interface and the Data Consumer Interface, and allows for more automation.
- Storage Component
    - Until developing this, we are assuming users are storing data themselves. Depending how acceptable this assumption is, we may need this component much earlier?

**Comment by milstan** [comment]
Thanx @jboileau99. This makes a lot of sense. What do others think?

It would be good to hear @noelmace on the question of attractivity for adoption of each of those options.

We should also think whether the first thing(s) we make provide a meaningfully complete feature-set (using it gives you some benefit on its own, in addition to your existing system). What do you think about that?

- do we (maybe) absolutely need to provide the Data Consumer interface to view requests and decide on them (how likely it is people already have those and can just use our Privacy Request Capture Interface)?

- or can we get away without it?

The alternative would be to go with the Privacy Computation Engine first, but that is possible only if people already have their own interface for privacy request capture and management (e.g. leto legal and similar) and provided we can interface with them.

**Comment by TheKinrar** [comment]
Seems to me like the Capture Component and the Mapping Component can't really be developed separately, but this depends on how we are going to refactor the architecture to take in to account this new way of plugging into an existing data storage.
The mapping will replace the storage component in a way, and technically it could be just an implementation of the storage component interface for example. Data Capture Component creates the metadata associated with what's in storage (or some DB when using mappings) so both seem quite useless without the other.

**Comment by milstan** [comment]
> Seems to me like the Capture Component and the Mapping Component can't really be developed separately, but this depends on how we are going to refactor the architecture to take into account this new way of plugging into an existing data storage.
> 
> The mapping will replace the storage component in a way, and technically it could be just an implementation of the storage component interface for example. Data Capture Component creates the metadata associated with what's in storage (or some DB when using mappings) so both seem quite useless without the other.

My idea here is to focus (for Q3) on relational databases: map their fields to captures and fragments. Then later (Q4) develop support for:
- document data bases
- and for using blidnnet devkit from the start of building a system, using it to also store data (in a document-database format directly supporting fragments and captures).

**Comment by jboileau99** [comment]
> We should also think whether the first thing(s) we make provide a meaningfully complete feature-set (using it gives you some benefit on its own, in addition to your existing system). What do you think about that?
> 
> * do we (maybe) absolutely need to provide the Data Consumer interface to view requests and decide on them (how likely it is people already have those and can just use our Privacy Request Capture Interface)?
> * or can we get away without it?

This is the other reason I think the Privacy Request Capture Interface makes sense to start with. It doesn't rely on other components in its most basic form but still provides the useful functionality of privacy requests for data subjects. Then once we have the mapping/storage and capture components, we could develop the data consumer interface to round out a complete feature set as described [here](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#data-consumer-interface).

The data consumer interface provides more than just viewing requests, right? There's also the _VIEW_AND_MANAGE_ and _CONFIGURE_ functionalities

> Seems to me like the Capture Component and the Mapping Component can't really be developed separately, but this depends on how we are going to refactor the architecture to take into account this new way of plugging into an existing data storage. The mapping will replace the storage component in a way, and technically it could be just an implementation of the storage component interface for example. Data Capture Component creates the metadata associated with what's in storage (or some DB when using mappings) so both seem quite useless without the other.

Ah ok, I think the mapping component as an implementation of the storage component makes sense. My thinking was mainly that whatever component achieves the mapping function should be developed earlier on so that it is always clear how the devkit can be integrated with other systems. But maybe it doesn't make sense to develop a mapping/storage component before there is much use for it outside of the component itself?

**Comment by milstan** [comment]
> The data consumer interface provides more than just viewing requests, right? There's also the _VIEW_AND_MANAGE_ and _CONFIGURE_ functionalities

@jboileau99 the idea here is to chose a viable subset of it, and if needed also refactor the architecure to obtain a minimal viable feasture-set. So, I don't think we need to really deliver all (i.e. view data might wait). But I think the part of letting them view/accept/deni requests (that is a part of Data Consumer Interface) might need to be developped together with the Privacy Request Capture Interface in order to really make sens for someone to start using it. Don't you think?

**Comment by milstan** [comment]
The more I read what you all write the more I think we need to slightly refactor the architecture to make a Metadata Engine component, that will do:
- the Mapping (db structure / input form structure to PRIV terms)
- subset of what the Storage component is supposed to do
- Subset of what the capture component is supposed to do - generating metadata in PRIV terms

**Comment by noelmace** [comment]
I updated #721 description following the MoSCoW priorities defined with the team instead of making a formal decision record, as this could still change in the futur.
    
For v0.1, this led us to (prioritized but all in parallel in order to optimize productivity - 1 project / 1 dev)

1. #772
2. #762
3. #778

**Comment by milstan** [comment]
I consider this issue done, as I think the priorities chosen are not overlaping with any (to me) known open source library/tool. On the go we might end-up using some open source libraries and intefracing us to them, but this is no reason to keep this issue open. So I am closing it.
