### ISSUE TITLE
📑 [Epic]: kickstart the privacy request capture interface

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#778]
## Description

Build:
1. a first operational web component following the local [privacy request capture interface](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#privacy-request-capture-interface) definition
2. and define the associated API specifications using mocks

> **warning**
>
> This Epic doesn't include the development of the global privacy request capture interface, but should still prepare its development.

[User Stories](https://github.com/blindnet-io/product-management/blob/main/user-stories/US-07-Privacy-request-capture-service.md) (1 and 2 not 3).

Must keep in mind and eventually implement all requirements from #720 

### Intended outcome

- have a minimal but operational user interface to make a transparency request using mocked API
- have a strong enough basis to develop following user stories

## Sub-tasks

- [x] blindnet-io/product-management#779
- [x] Define the PRIV typings
- [x] set-up a privacy request API mocking solution
- [x] blindnet-io/wc-priv-request#4
- [x] blindnet-io/wc-priv-request#5
- [x] Define properties and events
- [x] #811

## Stakeholders

- @jboileau99  for development
- @noelmace & @m4rk055 for mentoring, review and contribution whenever necessary
- @milstan for tracking and help

**Comment by jboileau99** [comment]
> * [ ]  build the Access privacy requesting definition UI

@noelmace as discussed this morning, will do the transparency action first for v0.1, instead of access

**Comment by noelmace** [comment]
After further discussion with Clémentine and Justin on this :point_up: , we agreed Justin should start with the transparency action IF designed enough by then, but shouldn't wait for it if not (therefore starting with Access), as there will be no actual communication with the PCE in v0.1.

**Comment by milstan** [comment]
few things to note (please ignore this comment if you arelady know them):

- The system may have to respond differently to certain TRANSPARENCY requests [after having already caputred information (when user is known, and authenticated, according to Art 15 of GDPR) and differently when before capturing any data (for an annonimous user, according to Arts 13 & 14 of GDPR).](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#general-vs-specific-interpretation-of-transparency-privacy-requests).

- @Clementinev suggested and I think it is a good idea to allow Organziations to showcase have some sort of bread-and-butter, common requests (Like "Do you have information on me", "Stop processing data on me",....) for easy access. Then, if user wants, they can also go throught the full wizard and choose every possible parameter (but it takes more time). Ideally the organziations can configure those common requests by providing a JSON file containing them. The component would then just (if needed) authenticate the user, and process the request.

**Comment by jboileau99** [comment]
Any remaining tasks/notes from this issue moved to #812
