### ISSUE TITLE
📑 [Epic]: updates on Privateform wording

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#786]
## Description

All wordings update for Privateform v1.0.7 and/or v1.0.8.

## Sub-tasks

- [x] https://github.com/blindnet-io/product-management/issues/749
- [x] https://github.com/blindnet-io/product-management/issues/744
- [x] https://github.com/blindnet-io/product-management/issues/739
- [x] https://github.com/blindnet-io/product-management/issues/654

## Stakeholders

- @noelmace for tracking
- @Clementinev for listing related issues

**Comment by Clementinev** [comment]
Fixes needed on #739 :
Small typo to fix : adding "s" to "Demandes" and "Requests" : 
<img width="1440" alt="Screenshot 2022-07-11 at 12 06 54" src="https://user-images.githubusercontent.com/89908145/178241365-5cdb3197-d0c0-4c04-be1f-f52f67351845.png">
<img width="1440" alt="Screenshot 2022-07-11 at 12 07 01" src="https://user-images.githubusercontent.com/89908145/178241374-c07c745c-19ba-4210-a474-511806a92af6.png">

**Comment by Clementinev** [comment]
Fix needed on #654:

1. [Email 1 user](https://docs.google.com/document/d/1fK0Pw-OkN1YLQ5rD1STdRzFk1mPNyTLjcYBKBLhirCc/edit#heading=h.6ju2px4vyzkm) added "to [client]"
**->** Works well for Loreto form, doesn't on other form -> **this should be applied to all forms**
