### ISSUE TITLE
📑 [Epic]: Users should view last form page (with legal consent and email address) when viewing/downloading submitted forms

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#788]
## Description

All issues regarding the viewing of last form page (with legal consent and email address) when viewing/downloading submitted forms, as Data Consumer on Received forms tab and as Submitter on GDPR access request

## Sub-tasks

- [x] https://github.com/blindnet-io/product-management/issues/686
- [x] https://github.com/blindnet-io/product-management/issues/740
- [x] https://github.com/blindnet-io/product-management/issues/746
