### ISSUE TITLE
📑 [Epic]: Define Diagrams and Sketches for Privacy Request Capture Interface

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#803]
## Description

This work is part of https://github.com/blindnet-io/product-management/issues/720

### Goal
Make diagrams and sketches for Privacy Request Capture Interface

The goal is to have : 
- diagrams for general workflows (for local and global service)
- one diagram per each demand (action) illustrating the eligible scope for each demand regarding data categories, processing categories, purposes, and other elements (for example for an access demand the user can choose among the data categories but not among processing categories nor purposes whereas for an object demand the user can choose among processing categories and purposes)
- Sketches of the interface

Document : [Figma link to diagrams and sketches](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=0%3A1)

## Sub-tasks

Local Privacy Request Capture Interface
- [x] https://github.com/blindnet-io/product-management/issues/734
- [x] https://github.com/blindnet-io/product-management/issues/804
- [x] https://github.com/blindnet-io/product-management/issues/805
- [x] https://github.com/blindnet-io/product-management/issues/809
- [x] https://github.com/blindnet-io/product-management/issues/864
- [ ] Issue to come -> Define Diagrams and Sketches for local OBJECT request
- [ ] Issue to come -> Define Diagrams and Sketches for local PORTABILITY request
- [ ] Issue to come -> Define Diagrams and Sketches for local RESTRICT request
- [ ]  Issue to come -> Define Diagrams and Sketches for local MODIFY request

Global Privacy Request Capture Interface
- [ ] #XXX
- [ ] #XXX

## Stakeholders

@Clementinev - in charge
@filipblnt @m4rk055 @jboileau99 - continuously involved in the work and needing the result of this work
@everyone - helping with feedback and testing on sketches

**Comment by milstan** [comment]
I suspect this issue to be done. I am closing it. @Clementinev  feel free to reopen if needed.
