### ISSUE TITLE
📑 [Epic]: Local Privacy Request Capture Interface

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/product-management#812]
## Description

Build:
- A web component to achieve the intended outcomes
- Storybook detailing and documenting component usage
- Test suite

### Intended outcome

- Interface for creating [Privacy Requests](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#privacy-request) and viewing [Privacy Responses](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#privacy-request-response)
- Fulfill all [user stories](https://github.com/blindnet-io/product-management/blob/main/user-stories/US-07-Privacy-request-capture-service.md), [interface sketches](https://github.com/blindnet-io/product-management/issues/803) excluding [US 07-3](https://github.com/blindnet-io/product-management/blob/main/user-stories/US-07-Privacy-request-capture-service.md#07-3-us-specific-to-global-privacy-request-capture-service), and requirements discussed [here](https://github.com/blindnet-io/product-management/issues/720)

## Sub-tasks

- [ ] #803
- [ ] blindnet-io/wc-priv-request#9
- [ ] blindnet-io/wc-priv-request#8
- [ ] blindnet-io/wc-priv-request#7
- [ ] blindnet-io/wc-priv-request#10
- [ ] blindnet-io/wc-priv-request#11 as mentioned [here](https://github.com/blindnet-io/product-management/issues/778#issuecomment-1179320094)
- [ ] blindnet-io/wc-priv-request#12
- [ ] Enforce accessibility
- [ ] Handle the different in response if a user is authenticated beforehand or not, discussed [here](https://github.com/blindnet-io/product-management/issues/778#issuecomment-1179320094)

## Stakeholders

- @jboileau99 Development
- @Clementinev Stories and interface sketches
- @noelmace & @m4rk055 Mentoring, review and contribution whenever necessary
- @milstan Tracking and help

**Comment by milstan** [comment]
this is done
