### ISSUE TITLE
Make Privacy Manager as a Zendesk Plugin

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#821]
## Description

Many companies use ZenDesk ([see documentation](https://developer.zendesk.com/documentation/apps/getting-started/zendesk-app-quick-start/)) to collect and manage Privacy Requests.

If we want blindnet DevKit to integrate in their existing workflow, and only help them gain automation of requests (or process most of them at lest semi-automatically), then we need to provide a ZenDesk aplication.

### Intended outcome

Clinets using ZenDesk for customer support can access all features of Privacy Manager (Data Subject Interface and Data Consumer Intefrace) throught ZenDesk

## Sub-tasks
- [ ] Study ZenDesk Documentation
- [ ] Build and test the ZenDesk application
- [ ] Discuss [partnership opportunites](https://www.zendesk.fr/partner/) with ZenDesk

## Stakeholders

@jboileau99 IMHO it is easier for us to build the first version of Data Consumer interface as a stand-alone thing, and only aim form ZenDesk compatibility later (in Q4). What do you think?
