### ISSUE TITLE
📑 [Epic]: Make Diagrams and Sketches for Data Consumer Interface

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#857]
## Description
This work is part of https://github.com/blindnet-io/product-management/issues/756

### Goal
Define Diagrams and Sketches for [Data Consumer Interface](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#data-consumer-interface) and for each type of request 

Document : [Figma link to Data Consumer Interface diagrams and sketches](https://www.figma.com/file/1hX1hlUrq0QTDjMmLJrDSK/Data-Consumer-Interface)

## Sub-tasks

- [ ] https://github.com/blindnet-io/product-management/issues/758
- [ ]  Issue to come -> Define Diagrams and Sketches for DELETE request
- [ ] Issue to come -> Define Diagrams and Sketches for TRANSPARENCY request
- [ ] Issue to come -> Define Diagrams and Sketches for ACCESS request
- [ ] Issue to come -> Define Diagrams and Sketches for REVOKE CONSENT request
- [ ] Issue to come -> Define Diagrams and Sketches for OBJECT request
- [ ] Issue to come -> Define Diagrams and Sketches for PORTABILITY request
- [ ] Issue to come -> Define Diagrams and Sketches for RESTRICT request
- [ ] Issue to come -> Define Diagrams and Sketches for MODIFY request

## Stakeholders

@Clementinev - in charge
@jboileau99 - continuously involved in the work and needing the result of this work
@everyone - helping with feedback and testing on sketches
