### ISSUE TITLE
📑 [RE/MAX Avantage] client's project development epic

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#872]
| Clients-management issue  | reference link                                             |
| --------------------- | -------------------------------------------------------------------- |
| Client’s epic  | https://github.com/blindnet-io/clients-management/issues/52  |
| Client’s requirement |  https://github.com/blindnet-io/clients-management/issues/59 |

## Product Requirements
_(the product currently covers)_

### Form Case 1

**Dossier vendeur** / Sales file
Sellers need to send their sales file with [these information](https://github.com/blindnet-io/clients-management/issues/52#issuecomment-1191261927) to client

**Timeframe:** Start Date: 2022-07-21 - Estimate Deadline: 2022-08-08 - Deadline: YYYY-MM-DD

#### Development steps
- [x] Ready for Development (_see requirements bellow_)
- [ ] Staging Release (v1.0.10)
- [ ] Production Release (v1.0.10)
- [ ] Form on client's PF account

#### Functional Requirements 

- https://github.com/blindnet-io/product-management/issues/823 **1/1**

#### Nonfunctional Requirements

- [x] @Clementinev creates PDF templates in french and english
- [ ] @noelmace make sure [personalization requirements](https://docs.google.com/document/d/1mH6ENf_fFoA_rz4thw_oCe9T46zejCvftDfGvx13THU/edit#) are ok during first form demonstration meeting
- [ ] @marko (or fusion) links form (with legal text and consent option) to client pf account

#### Following Improvements

  - [ ] { autolinked reference to a a product-management issue }

### Form Case 2

**TBD: dossier acheteur ?**

## Additional Requirements
_(the product currently does not cover and need additional dev)_

Client needs to be able to search through forms by properties (same need as [Loreto](https://github.com/blindnet-io/clients-management/issues/49))

- [x] https://github.com/blindnet-io/product-management/issues/858

### Following Improvements

  - [ ] { autolinked reference to a a product-management issue }

## Stakeholders

- Engineering Officer: @filipblnt @m4rk055 
- SE Officer: @noelmace 
- Account management: @timnicblind 
- Product/User Experience : @Clementinev

**Comment by noelmace** [comment]
@Clementinev Those are two different projects. We should have two different epics.
