### ISSUE TITLE
📑 [Skill Hunter] client’s project development epic

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#873]
| Clients-management issue  | reference link                                             |
| --------------------- | -------------------------------------------------------------------- |
| Client’s epic  | https://github.com/blindnet-io/clients-management/issues/57 |
| Client’s requirement | https://github.com/blindnet-io/clients-management/issues/64      |

## Product requirements 
_(the product currently covers)_

### Form Case 1

**Skill Hunter CV**
Create simple form with first name, last name and CV fields for candidates to send their CV to the client

**Timeframe:** Start Date: 2022-07-24 - Estimate Deadline: 2022-08-02 - Deadline: 2022-08-02

#### Development steps
- [x] Ready for Development (_see requirements bellow_)
- [x] Staging Release (v1.0.9)
- [x] Production Release (v1.0.9)
- [ ] Form on client's PF account

#### Functional Requirements 

- [x] https://github.com/blindnet-io/product-management/issues/841

#### Nonfunctional Requirements

- [x] @Clementinev  creates PDF templates in french and english
- [ ] @noelmace  make sure [personalization requirements](https://docs.google.com/document/d/1mH6ENf_fFoA_rz4thw_oCe9T46zejCvftDfGvx13THU/edit#) are ok during first form demonstration meeting
- [ ] @m4rk055  links form (with legal text and consent option) to client pf account

## Additional Requirements
_(the product currently does not cover and need additional dev)_ 

In a second time, personalize form's look-and-feel so it looks like as much as it can to client's website's form

- [ ] { autolinked reference to a a product-management issue }

## Stakeholders

- Engineering Officer: @filipblnt @m4rk055 
- SE Officer: @noelmace 
- Account management: @timnicblind 
- Product/User Experience : @Clementinev

**Comment by noelmace** [comment]
@Clementinev I believe those are 2 different projects, which should lead to two different epics.

The Client's requirements epic in clients-management is here to track all client's projects.

**Comment by Clementinev** [comment]
I think it is a lot to have one epic per form/additional requirement as it would almost be duplicate of the atomic "specification" issues.  If we take Loreto example, it would mean having 5 different epics (4 forms and additional requirement of search per appartement field), each epic having their own atomic "specification" issue. 

I was thinking what if we merge epic/atomic spec issue to have one per form/additional requirement without duplicate but we can't as an epic should not be put on the board because they can't be manage in one sprint as the tasks have different timeline and different stakeholders involved (e.g. form is developed on staging / put on prod / put on client's pf account ...)

Having one product epic per client following all forms/additional requirement seems easier and I think having everything dev related to a client a the glance is convenient - what do you think ?

**Comment by noelmace** [comment]
@Clementinev We already spent way too much time discussing this, and I don't think this is a priority now. Let's have this discussion another time. Please open a discussion issue in clients-management for that so we can avoid comments unrelated to this issue. I'll update it as I update the templates and documentation during (or after) your vacation.

**Comment by noelmace** [comment]
See https://github.com/blindnet-io/product-management/issues/884
