### ISSUE TITLE
⚙️ [Project]: RE/MAX - Dossier vendeur

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#882]
## Description

| Client's Epic      |  https://github.com/blindnet-io/clients-management/issues/52 |
| --------------------- | ---- |
| Client's Requirements | https://github.com/blindnet-io/clients-management/issues/59 |

Allow RE/MAX to collect documents from people wanting to sell a house/apartment (see https://github.com/blindnet-io/clients-management/issues/52#issuecomment-1191261927).

## Sub-tasks

- [x] https://github.com/blindnet-io/product-management/issues/823
- [x] https://github.com/blindnet-io/product-management/issues/848
- [x] https://github.com/blindnet-io/product-management/issues/858
- [x] https://github.com/blindnet-io/product-management/issues/866
- [x] https://github.com/blindnet-io/product-management/issues/877

## Stakeholders

- SE Officer: @noelmace
- Account management: @earvinblindnet 
- Product/User Experience: @Clementinev

**Comment by milstan** [comment]
done
