### ISSUE TITLE
⚙️ [Project]: Loreto - Locataire

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#885]
## Description

| Client's Epic         | https://github.com/blindnet-io/clients-management/issues/34 |
| --------------------- | ---- |
| Client's Requirements |  https://github.com/blindnet-io/clients-management/issues/49 |

Allow potential tenants to send information to Loreto.

## Sub-tasks

- [x] https://github.com/blindnet-io/product-management/issues/787
- [x] https://github.com/blindnet-io/product-management/issues/815
- [x] https://github.com/blindnet-io/product-management/issues/816
- [x] https://github.com/blindnet-io/product-management/issues/848

## Stakeholders

- SE Officer: @noelmace 
- Account management: @earvinblindnet 
- Product/User Experience: @Clementinev
