### ISSUE TITLE
⚙️ [Project]: Holtrop SLP - simple ID form

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#890]
## Description

> Client's Epic: https://github.com/blindnet-io/clients-management/issues/18

Allow Holtrop to collect ID documents and contact information.

## Sub-tasks

- [x] https://github.com/blindnet-io/product-management/issues/651
- [x] https://github.com/blindnet-io/product-management/issues/683
- [x] https://github.com/blindnet-io/product-management/issues/684

## Stakeholders

- SE Officer: @noelmace 
- Account management: @earvinblindnet 
- Product/User Experience: @Clementinev
