### ISSUE TITLE
⚙️ [Project]: Sagan - "retard de justice"

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#891]
## Description

> Client's Epic: https://github.com/blindnet-io/clients-management/issues/3

Create a new privateform with for Sagan Avocats, as a simple and direct replacement of their TypeForm for delayed justice dossiers.

## Sub-tasks

- [x] https://github.com/blindnet-io/clients-management/issues/10
- [x] https://github.com/blindnet-io/clients-management/issues/11
- [x] https://github.com/blindnet-io/clients-management/issues/12
- [x] https://github.com/blindnet-io/clients-management/issues/13
- [x] https://github.com/blindnet-io/clients-management/issues/14
- [x] https://github.com/blindnet-io/product-management/issues/630
- [x] https://github.com/blindnet-io/product-management/issues/629
- [x] https://github.com/blindnet-io/product-management/issues/628
- [x] https://github.com/blindnet-io/product-management/issues/627
- [x] recreate Sagan's account (lost password) and re-link the form to it
- [x] #898
- [x] https://github.com/blindnet-io/product-management/issues/633
- [x] https://github.com/blindnet-io/clients-management/issues/51
- [x] #902 
- [x] https://github.com/blindnet-io/product-management/issues/918
- [x] https://github.com/blindnet-io/product-management/issues/921
- [x] https://github.com/blindnet-io/product-management/issues/917
- [x] https://github.com/blindnet-io/product-management/issues/929
- [x] https://github.com/blindnet-io/product-management/issues/934
- [x] https://github.com/blindnet-io/product-management/issues/935
- [x] https://github.com/blindnet-io/product-management/issues/936
- [x] https://github.com/blindnet-io/product-management/issues/937
- [x] https://github.com/blindnet-io/product-management/issues/941

## Stakeholders

- SE Officer: @noelmace 
- Account management: @earvinblindnet @milstan 
- Product/User Experience: @Clementinev

**Comment by milstan** [comment]
done
