### ISSUE TITLE
📑 [Epic]: Implment MODIFY requests in DevKit

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#953]
## Description

The MODIFY requests allow Data Subjects to request modification of some of their data. The most common is the modification of address or bank account.

### Intended outcome

It is possible for Systems using DevKit to implement MODIFY in two ways, and it is possible to configure the DevKit to perform in one of those ways:
- **System's MODIFY**: The Data Subject, clicking on "MODIFY" gets a link directing them to a profile Page on the System's existing interface where they can edit their profile and change any data they want. This can be configured in the configuration component.
- **DevKit MODIFY**: The Data Subject specifies the new data to be inserted insted of the existing data

**DevKit MODIFY** works in the followign way:
- Selectors that can be affected by a MODIFY reuqest are clearly specified in the configuration component. For each, a primitive data-type is defined.
- In PRCI, the Data Subject is promted to choose the selectors they want to modify, and then to provide the new data.
- PCE, if the request is granted, issues intructions to replace existing data with new data provided by the Data Subject in the request
- LImitation: it works only with primitive data types (including strings), not with objects nor with arrays

## Sub-tasks

- [ ] System's MODIFY in PRCI (showing a link to "edit my profile")
- [ ] Implement DevKit MODIFY in PCE
- [ ] Implement DevKit MODIFY in PRCI
