### ISSUE TITLE
🔴 Build a more useful, easy to integrate version of DevKit

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#959]
## Description

This is the TOP PRIORITY issue in the Product line of work in Q4 2022.

### Intended outcome

In Q3 we built the first version of DevKit with a working (and impressive) demo. The goal for Q4 is to grow this version towards a more complete feature set (among the scope of our technical specs) that maximises:
- usefulness for clients in their real-life situations/scenarios
- ease of integration (the effort of integration justifies the usefulness - gain of time/money that the product offers)

### Build
- [ ] Authentication: Enable Data Subject during the process of request processing, and envale System/Components authentication when communicating around requests
- [ ] Configuration component (to allow configuring other components by a DPO/DC)
- [ ] PRCI is more versatile (customizable) and covers additional request types
- [ ] DCI shows timeline, can show recommendations and support more complex scenarios involving DPO validation and decision
- [ ] PCE works with Retention policies, and can load/offload Regulations
- [ ] Other relevant imporvments

These subtasks are further specified in concrete issues in corresponding component repositories.

### Document
- [ ] Each component has clear documentation, a how-to turotial
- [ ] There is a demo app, and a how-to-make tutorial allow anyone to make an app similar/same to the demo-app. Ideally this demo app is used by us (e.g. CV-collector app on our recruitment page)
- [ ] Devlopers give positive assessment of the ease-of-use and documentation

**Comment by noelmace** [comment]
> From @Vuk-BN on Oct. 10 by email

« _Please channel your efforts towards the tasks below, in the following order:_

_1. Documentation for the DevKit - further contribute and develop the available documentation to reflect all components in production and development of the DevKit_
_2. Tutorials for the Devkit - create a new and functioning demo app (e.g. CV-collector app for our recruitment process) with a tutorial that describes each development step_
_3. Github discussion board - develop an initial github discussion board with no less than 5 discussions or topics that an average developer might have when it comes to the integration of the DevKit_ »

I updated the associated section (Document and Onboard) accordingly.
