### ISSUE TITLE
⚪️ Each component has clear documentation, including a how-to tutorial

### ISSUE THREAD

**Issue by nweldev** [blindnet-io/product-management#962]
> Top Priority for DevRel on [Q4 2022](https://github.com/blindnet-io/communication-management/issues/195) (1/3) - see https://github.com/blindnet-io/product-management/issues/959

## Steps

- [x] https://github.com/blindnet-io/devrel-management/issues/89
- [x] https://github.com/blindnet-io/product-management/issues/980
- [ ] complete https://pc4w.blindnet.dev & the associated section of https://blindnet.dev
- [ ] complete storage documentation
- [ ] https://github.com/blindnet-io/devrel-management/issues/72
- [ ] simplify the introductory tutorial
- [ ] split the previous introductory tutorial into multiple how-to tutorials for each component
- [ ] document the data capture components
- [ ] document the new encryption components
- [ ] document access management / the new dashboard
