### ISSUE TITLE
DCI shows timeline, can show recommendations and support more complex scenarios involving DPO validation and decision

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/product-management#987]
Sub-issues:

- [ ] blindnet-io/privacy-components-web#135
- [ ] blindnet-io/privacy-components-web#131
- [ ] blindnet-io/privacy-components-web#168
- [ ] Ability to choose a motive when manually denying a request
