### ISSUE TITLE
PRCI is more versatile (customizable) and covers additional request types

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/product-management#988]
Sub-issues:
- [x] blindnet-io/privacy-components-web#164
- [x] blindnet-io/privacy-components-web#161
- [ ] blindnet-io/privacy-components-web#138
- [x] blindnet-io/privacy-components-web#128
- [x] blindnet-io/privacy-components-web#124
- [ ] blindnet-io/privacy-components-web#125
- [x] blindnet-io/privacy-components-web#126
- [x] blindnet-io/privacy-components-web#92
- [x] blindnet-io/privacy-components-web#93
- [x] blindnet-io/privacy-components-web#151
- [x] blindnet-io/privacy-components-web#153
- [ ] blindnet-io/privacy-components-web#127
