### ISSUE TITLE
Make it Easy to Intrgrate PRCI, DCI without storage in any web-page

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#997]
## Description

Currently, integration of PRCI in a webpage is really easy thanks to web components approach ✅ .

However, if we want any customization, it still requires quite an effort and poses certain limits. Our goal here is to make this smoother.

### Intended outcome

A client (modeled after our current clients pipeline) can quickly set-up, configure and cuspomize PRCI (and PCE) to their own needs. Some of those improvements are related to the configuration options of components, some to their layout, and others to the ways in shich the clients can set-up their own PCE instance, and others yet to the documentation - making it easy for the client to understand how to do it.

## Sub-tasks

- [x] blindnet-io/privacy-components-web/issues/173
- [ ] blindnet-io/privacy-components-web/issues/174
- [x] blindnet-io/privacy-components-web/issues/175
- [ ] blindnet-io/privacy-components-web/issues/176
- [x] blindnet-io/privacy-computation-engine/issues/23
- [x] blindnet-io/privacy-components-web/issues/151
- [ ] #1000
